# PS1_73_AfternoonShifts20260716_24.ps1
# Registers 13:00-22:00 afternoon shifts in ShiftEntries for the confirmed roster.
#
# This week (2026-07-16 Thu, 2026-07-17 Fri):
#   Elena Schlosser, Lubomir Stoyanov, Gunter Dinkelmann
#
# Next week Mon-Tue (2026-07-20, 2026-07-21):
#   Christian Koch, Elena Schlosser, Gunter Dinkelmann
#
# Next week Wed-Fri (2026-07-22, 2026-07-23, 2026-07-24):
#   Christian Koch, Gunter Dinkelmann, Lubomir Stoyanov
#
# Logic: UPSERT per (EmployeeId, ShiftDate)
#   - If a ShiftEntry already exists -> UPDATE ShiftStart/ShiftEnd to 13:00/22:00
#   - If not             -> INSERT ShiftType=WORKING, ShiftStart=13:00, ShiftEnd=22:00

$connStr = "Server=localhost\SQLEXPRESS;Database=GSDDashboard;Trusted_Connection=true;TrustServerCertificate=true;"

# ── Roster definition ─────────────────────────────────────────────────────────

$thisWeek  = @("2026-07-16","2026-07-17")
$nextMonTu = @("2026-07-20","2026-07-21")
$nextWedFr = @("2026-07-22","2026-07-23","2026-07-24")

# Name -> dates
$roster = @(
    [PSCustomObject]@{ Name="Elena Schlosser";    Dates=( $thisWeek + $nextMonTu ) },
    [PSCustomObject]@{ Name="Lubomir Stoyanov";   Dates=( $thisWeek + $nextWedFr ) },
    [PSCustomObject]@{ Name="Gunter Dinkelmann";  Dates=( $thisWeek + $nextMonTu + $nextWedFr ) },
    [PSCustomObject]@{ Name="Christian Koch";     Dates=( $nextMonTu + $nextWedFr ) }
)

$START = "13:00"
$END   = "22:00"

# ── Connect ───────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "=== PS1_73: Afternoon Shifts 13:00-22:00  (2026-07-16 to 2026-07-24) ===" -ForegroundColor Yellow
Write-Host ""

$conn = New-Object System.Data.SqlClient.SqlConnection($connStr)
try { $conn.Open(); Write-Host "DB: OK" -ForegroundColor Green }
catch { Write-Host "ERROR: $_" -ForegroundColor Red; exit 1 }

# ── Step 1: Lookup EmployeeIds ────────────────────────────────────────────────

Write-Host ""
Write-Host "--- Step 1: Lookup EmployeeIds ---" -ForegroundColor Cyan

$names    = $roster | ForEach-Object { $_.Name }
$nameList = ($names | ForEach-Object { "'" + $_.Replace("'","''") + "'" }) -join ","
$lookupSql = "SELECT EmployeeId, FullName FROM Employees WHERE FullName IN ($nameList)"
$lookupCmd = New-Object System.Data.SqlClient.SqlCommand($lookupSql, $conn)
$reader    = $lookupCmd.ExecuteReader()

$empMap = @{}
while ($reader.Read()) {
    $fn = ([string]$reader["FullName"]).Trim()
    $empMap[$fn] = [string]$reader["EmployeeId"]
}
$reader.Close()

foreach ($r in $roster) {
    if ($empMap.ContainsKey($r.Name)) {
        Write-Host ("  [OK]  {0,-30}  {1}" -f $r.Name, $empMap[$r.Name]) -ForegroundColor Green
    } else {
        Write-Host ("  [--]  {0,-30}  NOT FOUND" -f $r.Name) -ForegroundColor Yellow
    }
}

# ── Step 2: UPSERT per (EmployeeId, ShiftDate) ────────────────────────────────

Write-Host ""
Write-Host "--- Step 2: UPSERT ShiftEntries (ShiftStart=13:00, ShiftEnd=22:00) ---" -ForegroundColor Cyan

$insertSql = @"
INSERT INTO ShiftEntries
    (EmployeeId, ShiftDate, RawValue, ShiftType,
     ShiftStart, ShiftEnd, IsWicDuty, AutoGenerated, SourceModule)
VALUES
    (@EmployeeId, @ShiftDate, @RawValue, @ShiftType,
     @ShiftStart, @ShiftEnd, 0, 0, 'Manual')
"@

$updateSql = @"
UPDATE ShiftEntries
SET    ShiftStart = @ShiftStart,
       ShiftEnd   = @ShiftEnd
WHERE  EmployeeId = @EmployeeId
  AND  ShiftDate  = @ShiftDate
"@

$inserted = 0
$updated  = 0
$skipped  = 0
$failed   = 0

foreach ($r in $roster) {
    $eid = $empMap[$r.Name]
    if (-not $eid) {
        Write-Host ("  SKIP (not found)  {0}" -f $r.Name) -ForegroundColor Yellow
        $skipped += $r.Dates.Count
        continue
    }

    foreach ($dateStr in $r.Dates) {
        # Check if entry exists
        $checkCmd = New-Object System.Data.SqlClient.SqlCommand(
            "SELECT COUNT(*) FROM ShiftEntries WHERE EmployeeId = @EmployeeId AND ShiftDate = @ShiftDate",
            $conn)
        $checkCmd.Parameters.AddWithValue("@EmployeeId", $eid) | Out-Null
        $checkCmd.Parameters.AddWithValue("@ShiftDate",  [datetime]::Parse($dateStr)) | Out-Null
        $exists = [int]$checkCmd.ExecuteScalar()

        try {
            if ($exists -gt 0) {
                # UPDATE existing entry
                $cmd = New-Object System.Data.SqlClient.SqlCommand($updateSql, $conn)
                $cmd.Parameters.AddWithValue("@ShiftStart",  $START)                     | Out-Null
                $cmd.Parameters.AddWithValue("@ShiftEnd",    $END)                       | Out-Null
                $cmd.Parameters.AddWithValue("@EmployeeId",  $eid)                       | Out-Null
                $cmd.Parameters.AddWithValue("@ShiftDate",   [datetime]::Parse($dateStr)) | Out-Null
                $cmd.ExecuteNonQuery() | Out-Null
                Write-Host ("  UPDATE  {0,-30}  {1}  {2}-{3}" -f $r.Name, $dateStr, $START, $END) -ForegroundColor Cyan
                $updated++
            } else {
                # INSERT new entry
                $cmd = New-Object System.Data.SqlClient.SqlCommand($insertSql, $conn)
                $cmd.Parameters.AddWithValue("@EmployeeId", $eid)                        | Out-Null
                $cmd.Parameters.AddWithValue("@ShiftDate",  [datetime]::Parse($dateStr))  | Out-Null
                $cmd.Parameters.AddWithValue("@RawValue",   "WORKING")                   | Out-Null
                $cmd.Parameters.AddWithValue("@ShiftType",  "WORKING")                   | Out-Null
                $cmd.Parameters.AddWithValue("@ShiftStart", $START)                      | Out-Null
                $cmd.Parameters.AddWithValue("@ShiftEnd",   $END)                        | Out-Null
                $cmd.ExecuteNonQuery() | Out-Null
                Write-Host ("  INSERT  {0,-30}  {1}  {2}-{3}" -f $r.Name, $dateStr, $START, $END) -ForegroundColor Green
                $inserted++
            }
        } catch {
            Write-Host ("  ERROR   {0,-30}  {1}  {2}" -f $r.Name, $dateStr, $_) -ForegroundColor Red
            $failed++
        }
    }
}

# ── Verify ────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "--- Verify: 13:00-22:00 entries in range ---" -ForegroundColor Cyan

$vSql = @"
SELECT e.FullName, se.ShiftDate, se.ShiftType, se.ShiftStart, se.ShiftEnd
FROM ShiftEntries se
JOIN Employees e ON e.EmployeeId = se.EmployeeId
WHERE se.ShiftDate BETWEEN '2026-07-16' AND '2026-07-24'
  AND se.EmployeeId IN ($nameList)
ORDER BY se.ShiftDate, e.FullName
"@
$vCmd = New-Object System.Data.SqlClient.SqlCommand($vSql, $conn)
$vr   = $vCmd.ExecuteReader()
while ($vr.Read()) {
    $col = if ([string]$vr["ShiftStart"] -eq $START -and [string]$vr["ShiftEnd"] -eq $END) { "Green" } else { "Yellow" }
    Write-Host ("    {0,-30}  {1}  {2}  {3}-{4}" -f `
        [string]$vr["FullName"], [string]$vr["ShiftDate"], [string]$vr["ShiftType"],
        [string]$vr["ShiftStart"], [string]$vr["ShiftEnd"]) -ForegroundColor $col
}
$vr.Close()

$conn.Close()

# ── Summary ───────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host ("=== SUMMARY: Inserted={0}  Updated={1}  Skipped={2}  Errors={3} ===" -f $inserted, $updated, $skipped, $failed) `
    -ForegroundColor $(if ($failed -eq 0) { "Green" } else { "Red" })
Write-Host ""
Write-Host "Roster:"
Write-Host "  16-17 Jul (Thu-Fri) : Elena Schlosser, Lubomir Stoyanov, Gunter Dinkelmann"
Write-Host "  20-21 Jul (Mon-Tue) : Christian Koch, Elena Schlosser, Gunter Dinkelmann"
Write-Host "  22-24 Jul (Wed-Fri) : Christian Koch, Gunter Dinkelmann, Lubomir Stoyanov"
Write-Host ""
Write-Host "=== PS1_73 complete ===" -ForegroundColor Green
