# PS1_68_InsertShiftEntries20260714.ps1
# Inserts missing ShiftEntries for 2026-07-14 so Overview shows correct counts.
#
# Overview reads ShiftEntries.ShiftType (NOT SickLeaves).
# Already confirmed in ShiftEntries via "Absent Today" (11):
#   Sebastian Höck (SL), Marcus Rusch (AL), Timon Philippen (AL), Viktor Winter (AL),
#   Victoria Scholz (AL), Merlin Voss (AL), Erne Kis (AL), Duc Quy Huynh (AL),
#   Christian Koch (AL), Benjamin Bitz (AL), Ivonne Specht (AL)
#
# Missing from ShiftEntries (19):
#   SL  (5): Sharon Huber, Dominik Bajic, Pascal Dutz, Anisha Nellikka Panikkan, Mark Bachmann
#   AL  (4): Abdulrahman Aldera, Francois Sicot, Kamil Filipowicz, Kavinraj Pathmanathan
#   OFF (10): Eva-Liane Schliwa, Mustafa Deveci, Christian Pastors, Boris Kostov, Kemal Sener,
#             Veronika Kouwui, Zehra Sila Görgün, Arevig Ketenjian, Krishnendu Das, Yun Hee Oh

$connStr = "Server=localhost\SQLEXPRESS;Database=GSDDashboard;Trusted_Connection=true;TrustServerCertificate=true;"
$TODAY   = "2026-07-14"

# EmployeeIds confirmed from PS1_66 run output
$entries = @(
    # SL
    [PSCustomObject]@{ EmployeeId="9074576"; Name="Sharon Huber";              ShiftType="SL"  },
    [PSCustomObject]@{ EmployeeId="9126887"; Name="Dominik Bajic";             ShiftType="SL"  },
    [PSCustomObject]@{ EmployeeId="9074557"; Name="Pascal Dutz";               ShiftType="SL"  },
    [PSCustomObject]@{ EmployeeId="9124145"; Name="Anisha Nellikka Panikkan";  ShiftType="SL"  },
    [PSCustomObject]@{ EmployeeId="9122675"; Name="Mark Bachmann";             ShiftType="SL"  },
    # AL
    [PSCustomObject]@{ EmployeeId="9125519"; Name="Abdulrahman Aldera";        ShiftType="AL"  },
    [PSCustomObject]@{ EmployeeId="9128153"; Name="Francois Sicot";            ShiftType="AL"  },
    [PSCustomObject]@{ EmployeeId="9112561"; Name="Kamil Filipowicz";          ShiftType="AL"  },
    [PSCustomObject]@{ EmployeeId="9128149"; Name="Kavinraj Pathmanathan";     ShiftType="AL"  },
    # OFF
    [PSCustomObject]@{ EmployeeId="9074381"; Name="Eva-Liane Schliwa";         ShiftType="OFF" },
    [PSCustomObject]@{ EmployeeId="9114618"; Name="Mustafa Deveci";            ShiftType="OFF" },
    [PSCustomObject]@{ EmployeeId="9114617"; Name="Christian Pastors";         ShiftType="OFF" },
    [PSCustomObject]@{ EmployeeId="9124690"; Name="Boris Kostov";              ShiftType="OFF" },
    [PSCustomObject]@{ EmployeeId="9125526"; Name="Kemal Sener";               ShiftType="OFF" },
    [PSCustomObject]@{ EmployeeId="9124695"; Name="Veronika Kouwui";           ShiftType="OFF" },
    [PSCustomObject]@{ EmployeeId="9124687"; Name="Zehra Sila Görgün";         ShiftType="OFF" },
    [PSCustomObject]@{ EmployeeId="9076905"; Name="Arevig Ketenjian";          ShiftType="OFF" },
    [PSCustomObject]@{ EmployeeId="9084156"; Name="Krishnendu Das";            ShiftType="OFF" },
    [PSCustomObject]@{ EmployeeId="9106138"; Name="Yun Hee Oh";                ShiftType="OFF" }
)

Write-Host ""
Write-Host "=== PS1_68: Insert ShiftEntries $TODAY ===" -ForegroundColor Yellow
Write-Host "    5 SL + 4 AL + 10 OFF = 19 entries" -ForegroundColor Yellow
Write-Host ""

$conn = New-Object System.Data.SqlClient.SqlConnection($connStr)
try { $conn.Open(); Write-Host "DB: OK" -ForegroundColor Green }
catch { Write-Host "ERROR: $_" -ForegroundColor Red; exit 1 }

# ── Duplicate check ───────────────────────────────────────────────────────────

Write-Host ""
Write-Host "--- Duplicate check (ShiftEntries for $TODAY) ---" -ForegroundColor Cyan

$idList    = ($entries | ForEach-Object { "'" + $_.EmployeeId + "'" }) -join ","
$dupSql    = "SELECT EmployeeId, ShiftType FROM ShiftEntries WHERE ShiftDate = '$TODAY' AND EmployeeId IN ($idList)"
$dupCmd    = New-Object System.Data.SqlClient.SqlCommand($dupSql, $conn)
$dr        = $dupCmd.ExecuteReader()
$alreadyIn = @{}
while ($dr.Read()) {
    $eid = [string]$dr["EmployeeId"]
    $st  = [string]$dr["ShiftType"]
    $alreadyIn[$eid] = $st
}
$dr.Close()

if ($alreadyIn.Count -gt 0) {
    Write-Host ("  {0} employee(s) already have a ShiftEntry for $TODAY -- will skip:" -f $alreadyIn.Count) -ForegroundColor Yellow
    foreach ($kv in $alreadyIn.GetEnumerator()) {
        $n = ($entries | Where-Object { $_.EmployeeId -eq $kv.Key } | Select-Object -First 1).Name
        Write-Host ("    {0,-35}  existing={1}" -f $n, $kv.Value) -ForegroundColor DarkYellow
    }
} else {
    Write-Host "  No duplicates -- clean to insert." -ForegroundColor Green
}

# ── INSERT ────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "--- INSERT into ShiftEntries ---" -ForegroundColor Cyan

$insertSql = @"
INSERT INTO ShiftEntries
    (EmployeeId, ShiftDate, RawValue, ShiftType,
     ShiftStart, ShiftEnd, IsWicDuty, AutoGenerated, SourceModule)
VALUES
    (@EmployeeId, @ShiftDate, @RawValue, @ShiftType,
     NULL, NULL, 0, 0, 'Manual')
"@

$inserted = 0
$skipped  = 0
$failed   = 0

foreach ($entry in $entries) {
    if ($alreadyIn.ContainsKey($entry.EmployeeId)) {
        Write-Host ("  SKIP  {0,-35}  already has {1} for $TODAY" -f $entry.Name, $alreadyIn[$entry.EmployeeId]) -ForegroundColor DarkYellow
        $skipped++; continue
    }

    try {
        $cmd = New-Object System.Data.SqlClient.SqlCommand($insertSql, $conn)
        $cmd.Parameters.AddWithValue("@EmployeeId", $entry.EmployeeId)  | Out-Null
        $cmd.Parameters.AddWithValue("@ShiftDate",  [datetime]::Parse($TODAY)) | Out-Null
        $cmd.Parameters.AddWithValue("@RawValue",   $entry.ShiftType)   | Out-Null
        $cmd.Parameters.AddWithValue("@ShiftType",  $entry.ShiftType)   | Out-Null
        $cmd.ExecuteNonQuery() | Out-Null

        Write-Host ("  INSERT  {0,-35}  {1}" -f $entry.Name, $entry.ShiftType) -ForegroundColor Green
        $inserted++
    } catch {
        Write-Host ("  ERROR   {0,-35}  {1}" -f $entry.Name, $_) -ForegroundColor Red
        $failed++
    }
}

# ── Verify ────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "--- Verify ---" -ForegroundColor Cyan

$vSql = @"
SELECT ShiftType, COUNT(*) AS Cnt
FROM ShiftEntries
WHERE ShiftDate = '$TODAY'
  AND ShiftType IN ('SL','AL','OFF','OL','CD','UL')
GROUP BY ShiftType
ORDER BY ShiftType
"@
$vCmd = New-Object System.Data.SqlClient.SqlCommand($vSql, $conn)
$vr   = $vCmd.ExecuteReader()
Write-Host "  ShiftEntries counts for $TODAY (absence types):" -ForegroundColor Cyan
while ($vr.Read()) {
    Write-Host ("    {0,-6}  {1}" -f [string]$vr["ShiftType"], [string]$vr["Cnt"]) -ForegroundColor White
}
$vr.Close()

$conn.Close()

Write-Host ""
Write-Host ("=== SUMMARY: Inserted={0}  Skipped={1}  Errors={2} ===" -f $inserted, $skipped, $failed) `
    -ForegroundColor $(if ($failed -eq 0) { "Green" } else { "Red" })
Write-Host ""
Write-Host "Overview should now show: SL=6  AL=12  OFF=10" -ForegroundColor Cyan
Write-Host "(Refresh the browser after running)" -ForegroundColor DarkCyan
Write-Host ""
Write-Host "=== PS1_68 complete ===" -ForegroundColor Green
