# PS1_25_DiagnosticAccept.ps1
# Check DB columns needed by SubstitutionModule.cs, then test the accept endpoint.
# No Unicode, no here-strings.

$cs = "Server=localhost\SQLEXPRESS;Database=GSDDashboard;Integrated Security=true;TrustServerCertificate=yes;"

function RunQuery {
    param([string]$Label, [string]$Sql)
    Write-Host ""
    Write-Host "--- $Label ---" -ForegroundColor Cyan
    $conn = New-Object System.Data.SqlClient.SqlConnection($cs)
    try {
        $conn.Open()
        $cmd = $conn.CreateCommand()
        $cmd.CommandText = $Sql
        $cmd.CommandTimeout = 15
        $r = $cmd.ExecuteReader()
        $cols = @(); for ($i = 0; $i -lt $r.FieldCount; $i++) { $cols += $r.GetName($i) }
        Write-Host ($cols -join "  |  ") -ForegroundColor DarkGray
        $rowCount = 0
        while ($r.Read()) {
            $vals = @()
            for ($i = 0; $i -lt $r.FieldCount; $i++) {
                $vals += if ($r.IsDBNull($i)) { "NULL" } else { [string]$r[$i] }
            }
            Write-Host ($vals -join "  |  ")
            $rowCount++
        }
        Write-Host "($rowCount rows)" -ForegroundColor DarkGray
    } catch {
        Write-Host "ERROR: $_" -ForegroundColor Red
    } finally {
        $conn.Close()
    }
}

Write-Host ""
Write-Host "============================================" -ForegroundColor Yellow
Write-Host "  PS1_25: ACCEPT ENDPOINT DIAGNOSTIC" -ForegroundColor Yellow
Write-Host "============================================" -ForegroundColor Yellow

# 1. ShiftEntries columns
RunQuery "1. ShiftEntries columns" @"
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ShiftEntries'
ORDER BY COLUMN_NAME
"@

# 2. SubstitutionHistory columns
RunQuery "2. SubstitutionHistory columns" @"
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SubstitutionHistory'
ORDER BY COLUMN_NAME
"@

# 3. Check specific columns SubstitutionModule.cs needs
Write-Host ""
Write-Host "--- 3. Columns SubstitutionModule.cs requires ---" -ForegroundColor Cyan
$conn2 = New-Object System.Data.SqlClient.SqlConnection($cs)
$conn2.Open()
$checks = @(
    @{ table = "ShiftEntries";       col = "IsWicDuty" },
    @{ table = "ShiftEntries";       col = "SourceModule" },
    @{ table = "ShiftEntries";       col = "AutoGenerated" },
    @{ table = "ShiftEntries";       col = "AgentTask" },
    @{ table = "ShiftEntries";       col = "SourceSheet" },
    @{ table = "ShiftEntries";       col = "ShiftType" },
    @{ table = "ShiftEntries";       col = "ShiftDate" },
    @{ table = "ShiftEntries";       col = "EmployeeId" },
    @{ table = "SubstitutionHistory"; col = "SourceType" },
    @{ table = "SubstitutionHistory"; col = "AssignedAt" },
    @{ table = "SubstitutionHistory"; col = "Date" },
    @{ table = "SubstitutionHistory"; col = "LocationCode" },
    @{ table = "SubstitutionHistory"; col = "EmployeeId" }
)
foreach ($c in $checks) {
    $cmd2 = $conn2.CreateCommand()
    $cmd2.CommandText = "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='" + $c.table + "' AND COLUMN_NAME='" + $c.col + "'"
    $exists = [int]$cmd2.ExecuteScalar()
    $status = if ($exists -eq 1) { "OK  " } else { "MISSING" }
    $color  = if ($exists -eq 1) { "Green" } else { "Red" }
    Write-Host ("  [{0}] {1}.{2}" -f $status, $c.table, $c.col) -ForegroundColor $color
}
$conn2.Close()

# 4. Check WicLocations.IsActive column (used in SubstitutionModule.cs line 31)
RunQuery "4. WicLocations.IsActive check" @"
SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'WicLocations' AND COLUMN_NAME = 'IsActive'
"@

# 5. Sample row from SubstitutionHistory (confirm table exists and has rows)
RunQuery "5. SubstitutionHistory top 5" @"
SELECT TOP 5 * FROM SubstitutionHistory ORDER BY Id DESC
"@

# 6. Verify employee 9078602 exists
RunQuery "6. Employee 9078602 lookup" @"
SELECT EmployeeId, FirstName, LastName, PrimaryRole FROM Employees WHERE EmployeeId = '9078602'
"@

# 7. Verify location exists
RunQuery "7. Arnsberg location lookup" @"
SELECT LocationCode, DisplayName, IsActive FROM WicLocations WHERE LocationCode LIKE '%Arnsberg%'
"@

# 8. Test the accept endpoint via HTTP
Write-Host ""
Write-Host "--- 8. POST /api/wic/substitutes/accept (test call) ---" -ForegroundColor Cyan
$body = '{"employeeId":"9078602","locationCode":"DE~59821~Arnsberg~Hellefelder Str. 8","date":"2026-06-16","shiftStart":null,"shiftEnd":null,"sourceType":"SSP"}'
try {
    $resp = Invoke-WebRequest -Uri "http://localhost:5000/api/wic/substitutes/accept" `
        -Method POST `
        -Body $body `
        -ContentType "application/json" `
        -UseBasicParsing `
        -TimeoutSec 15
    Write-Host "  HTTP $($resp.StatusCode)" -ForegroundColor Green
    Write-Host "  Response: $($resp.Content)" -ForegroundColor Green
} catch {
    $sc = if ($_.Exception.Response) { [int]$_.Exception.Response.StatusCode } else { "N/A" }
    Write-Host "  HTTP $sc  ERROR: $($_.Exception.Message)" -ForegroundColor Red
    if ($_.Exception.Response) {
        try {
            $stream = $_.Exception.Response.GetResponseStream()
            $reader = New-Object System.IO.StreamReader($stream)
            $errBody = $reader.ReadToEnd()
            Write-Host "  Body: $errBody" -ForegroundColor Red
        } catch {}
    }
}

Write-Host ""
Write-Host "============================================" -ForegroundColor Yellow
Write-Host "  PS1_25 complete" -ForegroundColor Yellow
Write-Host "============================================" -ForegroundColor Yellow
