# PS1_35_UpdateShifts20260622.ps1
# Applies BO List + Absence Overview for 2026-06-22 (Monday)
# Tables: ShiftEntries (UPSERT), SickLeaves (IF NOT EXISTS), WicShiftEntries (UPSERT)

$cs   = "Server=localhost\SQLEXPRESS;Database=GSDDashboard;Trusted_Connection=true;TrustServerCertificate=true;"
$date = "2026-06-22"

# ─── helpers ──────────────────────────────────────────────────────────────────

function Invoke-Sql {
    param($sql)
    $conn = New-Object System.Data.SqlClient.SqlConnection($cs)
    $conn.Open()
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = $sql
    try   { $r = $cmd.ExecuteNonQuery() }
    catch { Write-Host "  ERR: $_" -ForegroundColor Red; $r = -1 }
    $conn.Close()
    return $r
}

function Upsert-Shift {
    param($eid, $d, $st, $ss, $se, $loc)
    $ssQ = if ($ss)  { "'$ss'"  } else { "NULL" }
    $seQ = if ($se)  { "'$se'"  } else { "NULL" }
    $lQ  = if ($loc) { "'$loc'" } else { "NULL" }
    $sql = "IF EXISTS (SELECT 1 FROM ShiftEntries WHERE EmployeeId='$eid' AND ShiftDate='$d') " +
           "UPDATE ShiftEntries " +
           "SET ShiftType='$st', ShiftStart=$ssQ, ShiftEnd=$seQ, LocationId=$lQ, SourceModule='PS1_35' " +
           "WHERE EmployeeId='$eid' AND ShiftDate='$d' " +
           "ELSE " +
           "INSERT INTO ShiftEntries " +
           "(EmployeeId, ShiftDate, ShiftType, ShiftStart, ShiftEnd, LocationId, AutoGenerated, SourceModule) " +
           "VALUES ('$eid', '$d', '$st', $ssQ, $seQ, $lQ, 0, 'PS1_35')"
    $r = Invoke-Sql $sql
    $tag = if ($r -gt 0) { "OK" } else { "no-change" }
    Write-Host ("  SHIFT  {0,-12} {1,-10} {2}" -f $eid, $st, $tag)
}

function Insert-Leave {
    param($eid, $fd, $ld, $lt, $note)
    $nQ = if ($note) { "'$note'" } else { "NULL" }
    $sql = "IF NOT EXISTS (SELECT 1 FROM SickLeaves WHERE EmployeeId='$eid' AND FirstDay='$fd' AND LeaveType='$lt') " +
           "INSERT INTO SickLeaves " +
           "(EmployeeId, FirstDay, LastDay, DurationDays, LeaveType, Comments, SourceSheet, CreatedAt) " +
           "VALUES ('$eid', '$fd', '$ld', 1, '$lt', $nQ, 'PS1_35', GETUTCDATE())"
    $r = Invoke-Sql $sql
    $tag = if ($r -gt 0) { "INSERTED" } else { "exists" }
    Write-Host ("  LEAVE  {0,-12} {1,-8} {2}" -f $eid, $lt, $tag)
}

function Upsert-Vwic {
    param($eid, $d)
    $sql = "IF EXISTS (SELECT 1 FROM WicShiftEntries WHERE EmployeeId='$eid' AND ShiftDate='$d') " +
           "UPDATE WicShiftEntries " +
           "SET SupportLocation='VWIC', WorkingShift='07:00 - 18:00', IsOnSite=1, Task='VWIC' " +
           "WHERE EmployeeId='$eid' AND ShiftDate='$d' " +
           "ELSE " +
           "INSERT INTO WicShiftEntries " +
           "(EmployeeId, ShiftDate, DayOfWeek, SupportLocation, WorkingShift, IsOnSite, IsGSDDay, IsOffDay, Task) " +
           "VALUES ('$eid', '$d', 'Monday', 'VWIC', '07:00 - 18:00', 1, 0, 0, 'VWIC')"
    $r = Invoke-Sql $sql
    $tag = if ($r -gt 0) { "OK" } else { "no-change" }
    Write-Host ("  VWIC   {0,-12} {1}" -f $eid, $tag)
}

# ─────────────────────────────────────────────────────────────────────────────
# TASK 1  Absences 2026-06-22
# ─────────────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "TASK 1: Absences $date" -ForegroundColor Yellow

Write-Host " SL (Sick Leave)"
Upsert-Shift "9074563" $date "SL" $null $null $null  # Ralf Turski
Insert-Leave "9074563" $date $date "SL" $null

Upsert-Shift "9074373" $date "SL" $null $null $null  # Duc Quy Huynh
Insert-Leave "9074373" $date $date "SL" $null

Upsert-Shift "4451020" $date "SL" $null $null $null  # Ivonne Specht
Insert-Leave "4451020" $date $date "SL" $null

Upsert-Shift "9119463" $date "SL" $null $null $null  # Jonathan Freudenthaler
Insert-Leave "9119463" $date $date "SL" $null

Upsert-Shift "9085123" $date "SL" $null $null $null  # Anil Bedzeti
Insert-Leave "9085123" $date $date "SL" $null

Upsert-Shift "9074557" $date "SL" $null $null $null  # Pascal Dutz
Insert-Leave "9074557" $date $date "SL" $null

Upsert-Shift "9129428" $date "SL" $null $null $null  # Binod Dutta
Insert-Leave "9129428" $date $date "SL" $null

Upsert-Shift "9126882" $date "SL" $null $null $null  # Khaled Alali
Insert-Leave "9126882" $date $date "SL" $null

Upsert-Shift "9107616" $date "SL" $null $null $null  # Klaus Friedrich
Insert-Leave "9107616" $date $date "SL" $null

Upsert-Shift "9122675" $date "SL" $null $null $null  # Mark Bachmann
Insert-Leave "9122675" $date $date "SL" $null

Upsert-Shift "9117836" $date "SL" $null $null $null  # Suhrab Sadieqy
Insert-Leave "9117836" $date $date "SL" $null

Upsert-Shift "9133995" $date "SL" $null $null $null  # Viktor Winter
Insert-Leave "9133995" $date $date "SL" $null

Write-Host " AL (Annual Leave)"
Upsert-Shift "9122679" $date "AL"      $null $null $null  # Hamyaz Pathan
Insert-Leave "9122679" $date $date "AL" $null

Upsert-Shift "9132079" $date "AL"      $null $null $null  # Sebastian Lewandowski
Insert-Leave "9132079" $date $date "AL" $null

Upsert-Shift "9132075" $date "AL"      $null $null $null  # Felix Spindler
Insert-Leave "9132075" $date $date "AL" $null

Upsert-Shift "9130657" $date "HALF_AL" $null $null $null  # Dmytro Shelikhov - half day
Insert-Leave "9130657" $date $date "AL" "half day"

Upsert-Shift "9106138" $date "UL"      $null $null $null  # Yun Hee Oh - unpaid leave
Insert-Leave "9106138" $date $date "UL" $null

Write-Host " OFF / OL / CD"
Upsert-Shift "9074381" $date "OFF" $null $null $null  # Eva-Liane Schliwa
Upsert-Shift "9074535" $date "OFF" $null $null $null  # Lubomir Stoyanov
Upsert-Shift "9074348" $date "OFF" $null $null $null  # Asal Wardaastiani Azar
Upsert-Shift "9114618" $date "OFF" $null $null $null  # Mustafa Deveci
Upsert-Shift "9124687" $date "OFF" $null $null $null  # Zehra Sila Gorgeun
Upsert-Shift "9124695" $date "OFF" $null $null $null  # Veronika Kouwui
Upsert-Shift "9125526" $date "OFF" $null $null $null  # Kemal Sener
Upsert-Shift "9126886" $date "OFF" $null $null $null  # Negin Bazmi (Task 2 will add times)

Write-Host " Night shift"
Upsert-Shift "9074592" $date "WORKING" $null $null $null  # Victoria Scholz

# ─────────────────────────────────────────────────────────────────────────────
# TASK 2  BO List agents 2026-06-22
# ─────────────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "TASK 2: BO List agents $date" -ForegroundColor Yellow

Upsert-Shift "9074330" $date "WORKING" "08:00" "17:00" $null          # Adnan Lelic
Upsert-Shift "9074350" $date "WORKING" "07:00" "16:00" $null          # Baschir Mahrufi
Upsert-Shift "9074518" $date "WORKING" "08:00" "17:00" $null          # Javier Sang
Upsert-Shift "9074582" $date "WORKING" "07:00" "16:00" $null          # Stefan Becker
Upsert-Shift "3193174" $date "WORKING" "08:00" "17:00" $null          # Anifa Ngcongo
Upsert-Shift "9124145" $date "WORKING" "08:00" "17:00" $null          # Anisha Nellikka Panikkan
Upsert-Shift "9133997" $date "WORKING" "08:00" "17:00" $null          # Kai Erik Kumlehn
Upsert-Shift "9132077" $date "WORKING" "08:00" "17:00" "Pfaffenhofen" # Mohamad Nasir Amany
Upsert-Shift "9124691" $date "WORKING" "08:00" "17:00" $null          # Sina Sidharthan
Upsert-Shift "9126886" $date "OFF"     "07:00" "16:00" $null          # Negin Bazmi (override, adds times)
Upsert-Shift "9128153" $date "WORKING" "08:00" "17:00" "Bamberg"      # Francois Sicot (BAG)
Upsert-Shift "9129429" $date "WORKING" "08:00" "17:00" "Helmstedt"    # Senthuran Shanmugalingam (Avacon)
Upsert-Shift "9130643" $date "WORKING" "08:00" "17:00" $null          # Lukas Schiefele
Upsert-Shift "9129441" $date "WORKING" "08:00" "17:00" $null          # Ahmad Dabbas
Upsert-Shift "9074345" $date "WORKING" "08:00" "15:00" $null          # Angelika Weber

Write-Host " Adnan Lelic AL 2026-06-25"
Upsert-Shift "9074330" "2026-06-25" "AL" $null $null $null
Insert-Leave "9074330" "2026-06-25" "2026-06-25" "AL" $null

# ─────────────────────────────────────────────────────────────────────────────
# TASK 3  vWIC assignments 2026-06-22
# ─────────────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "TASK 3: vWIC assignments $date" -ForegroundColor Yellow

Upsert-Vwic "9074375" $date   # Elena Schlosser
Upsert-Vwic "3193177" $date   # Gunter Dinkelmann
Upsert-Vwic "3193175" $date   # Isloodien Hurchem Lawrence

Write-Host ""
Write-Host "Done." -ForegroundColor Green
