# query_patterns.ps1 - Read-only diagnostics for Jul 2026 schedule mapping
# Uses System.Data.SqlClient (no Invoke-Sqlcmd per handoff rules)
$cs = "Server=localhost\SQLEXPRESS;Database=GSDDashboard;Integrated Security=true;TrustServerCertificate=yes;"

function Run-Query {
    param([string]$label, [string]$sql)
    Write-Host ""
    Write-Host "=== $label ===" -ForegroundColor Cyan
    $c = New-Object System.Data.SqlClient.SqlConnection($cs)
    $c.Open()
    $cmd = $c.CreateCommand()
    $cmd.CommandText = $sql
    $cmd.CommandTimeout = 60
    $reader = $cmd.ExecuteReader()
    $dt = New-Object System.Data.DataTable
    $dt.Load($reader)
    $c.Close()
    if ($dt.Rows.Count -eq 0) {
        Write-Host "  (no rows)" -ForegroundColor DarkGray
    } else {
        $dt | Format-Table -AutoSize | Out-String -Width 500
    }
}

# Q1: All active employees (for name matching)
Run-Query "ALL ACTIVE EMPLOYEES" @"
SELECT EmployeeId, FullName, FirstName, LastName, PrimaryRole, TeamLeadName, IsActive
FROM Employees
WHERE IsActive = 1
ORDER BY FullName
"@

# Q2: All WicLocations (for WIC occupancy matching)
Run-Query "ALL WIC LOCATIONS" @"
SELECT Id, LocationCode, DisplayName, City, Country, LocationCodeLegacy, IsActive
FROM WicLocations
ORDER BY Country, DisplayName
"@

# Q3: SickLeaves for 2026-06-25 through 2026-07-02
Run-Query "SICKLEAVES JUN25-JUL2" @"
SELECT Id, EmployeeId, FirstName, LastName,
       CONVERT(varchar,FirstDay,23) AS FirstDay,
       CONVERT(varchar,LastDay,23)  AS LastDay,
       DurationDays, LeaveType, SourceSheet
FROM SickLeaves
WHERE FirstDay <= '2026-07-02' AND LastDay >= '2026-06-25'
ORDER BY FirstDay, LastName
"@

# Q4: ShiftEntries for Jun 25-27 (SL pattern sample)
Run-Query "SHIFTENTRIES SL JUN25-27" @"
SELECT se.Id, se.EmployeeId, CONVERT(varchar,se.ShiftDate,23) AS ShiftDate,
       se.ShiftType, se.AgentTask, se.LocationId, se.SourceModule, se.AutoGenerated
FROM ShiftEntries se
WHERE se.ShiftDate BETWEEN '2026-06-25' AND '2026-06-27'
  AND se.ShiftType = 'SL'
ORDER BY se.ShiftDate, se.EmployeeId
"@

# Q5: ShiftEntries for Jun 25 - all types (to see full picture)
Run-Query "SHIFTENTRIES ALL JUN25" @"
SELECT se.ShiftType, COUNT(*) AS Cnt
FROM ShiftEntries se
WHERE se.ShiftDate = '2026-06-25'
GROUP BY se.ShiftType
ORDER BY Cnt DESC
"@

# Q6: WicShiftEntries for Jun 25 (to see existing WIC assignment pattern)
Run-Query "WICSHIFTENTRIES JUN25" @"
SELECT TOP 30 wse.Id, wse.EmployeeId,
       CONVERT(varchar,wse.ShiftDate,23) AS ShiftDate,
       wse.SupportLocation, wse.WorkingShift, wse.IsOnSite,
       wse.IsGSDDay, wse.Task, wse.DayOfWeek
FROM WicShiftEntries wse
WHERE wse.ShiftDate = '2026-06-25'
ORDER BY wse.SupportLocation
"@

# Q7: ShiftEntries already for Jul 2 (check what exists before we insert)
Run-Query "SHIFTENTRIES JUL2 EXISTING" @"
SELECT se.Id, se.EmployeeId, e.FullName, se.ShiftType,
       se.ShiftStart, se.ShiftEnd, se.AgentTask, se.SourceModule, se.AutoGenerated
FROM ShiftEntries se
LEFT JOIN Employees e ON e.EmployeeId = se.EmployeeId
WHERE se.ShiftDate = '2026-07-02'
ORDER BY se.ShiftType, e.FullName
"@

# Q8: WicShiftEntries already for Jul 2
Run-Query "WICSHIFTENTRIES JUL2 EXISTING" @"
SELECT wse.Id, wse.EmployeeId, e.FullName,
       wse.SupportLocation, wse.WorkingShift, wse.IsOnSite, wse.Task
FROM WicShiftEntries wse
LEFT JOIN Employees e ON e.EmployeeId = wse.EmployeeId
WHERE wse.ShiftDate = '2026-07-02'
ORDER BY wse.SupportLocation
"@

# Q9: SickLeaves already for Jul 2
Run-Query "SICKLEAVES JUL2 EXISTING" @"
SELECT sl.Id, sl.EmployeeId, sl.FirstName, sl.LastName,
       CONVERT(varchar,sl.FirstDay,23) AS FirstDay,
       CONVERT(varchar,sl.LastDay,23) AS LastDay, sl.LeaveType
FROM SickLeaves sl
WHERE sl.FirstDay = '2026-07-02' OR sl.LastDay = '2026-07-02'
ORDER BY sl.LastName
"@

# Q10: Distinct AgentTask values used (to confirm naming convention)
Run-Query "AGENTTASK VALUES USED" @"
SELECT AgentTask, COUNT(*) AS Cnt
FROM ShiftEntries
WHERE AgentTask IS NOT NULL
GROUP BY AgentTask
ORDER BY Cnt DESC
"@

Write-Host ""
Write-Host "=== Done ===" -ForegroundColor Green
