using GSDDashboard.API.Data;
using GSDDashboard.API.Data.Models;
using Microsoft.EntityFrameworkCore;

namespace GSDDashboard.API.Services;

public class ShiftSyncService
{
    private readonly GSDContext _db;

    public ShiftSyncService(GSDContext db) => _db = db;

    public async Task SyncSickLeaveAsync(string employeeId, DateOnly dateFrom, DateOnly dateTo, int sourceId)
    {
        for (var d = dateFrom; d <= dateTo; d = d.AddDays(1))
        {
            if (d.DayOfWeek == DayOfWeek.Saturday || d.DayOfWeek == DayOfWeek.Sunday) continue;

            var existing = await _db.ShiftEntries.FirstOrDefaultAsync(x => x.EmployeeId == employeeId && x.ShiftDate == d);
            if (existing != null)
            {
                existing.PreviousStatus = existing.ShiftType;
                existing.ShiftType = "SL";
                existing.AutoGenerated = true;
                existing.SourceModule = "SickLeave";
                existing.SourceId = sourceId;
            }
            else
            {
                _db.ShiftEntries.Add(new ShiftEntry
                {
                    EmployeeId = employeeId,
                    ShiftDate = d,
                    ShiftType = "SL",
                    AutoGenerated = true,
                    SourceModule = "SickLeave",
                    SourceId = sourceId
                });
            }
        }
        await _db.SaveChangesAsync();
    }

    public async Task SyncVacationAsync(string employeeId, DateOnly dateFrom, DateOnly dateTo, int sourceId)
    {
        for (var d = dateFrom; d <= dateTo; d = d.AddDays(1))
        {
            if (d.DayOfWeek == DayOfWeek.Saturday || d.DayOfWeek == DayOfWeek.Sunday) continue;

            var existing = await _db.ShiftEntries.FirstOrDefaultAsync(x => x.EmployeeId == employeeId && x.ShiftDate == d);
            if (existing != null)
            {
                existing.PreviousStatus = existing.ShiftType;
                existing.ShiftType = "AL";
                existing.AutoGenerated = true;
                existing.SourceModule = "Vacation";
                existing.SourceId = sourceId;
            }
            else
            {
                _db.ShiftEntries.Add(new ShiftEntry
                {
                    EmployeeId = employeeId,
                    ShiftDate = d,
                    ShiftType = "AL",
                    AutoGenerated = true,
                    SourceModule = "Vacation",
                    SourceId = sourceId
                });
            }
        }
        await _db.SaveChangesAsync();
    }

    public async Task RevertSickLeaveAsync(string employeeId, DateOnly dateFrom, DateOnly dateTo, int sourceId)
    {
        var entries = await _db.ShiftEntries
            .Where(x => x.EmployeeId == employeeId
                     && x.ShiftDate >= dateFrom
                     && x.ShiftDate <= dateTo
                     && x.SourceModule == "SickLeave"
                     && x.SourceId == sourceId)
            .ToListAsync();

        foreach (var e in entries)
        {
            if (e.PreviousStatus != null)
            {
                e.ShiftType = e.PreviousStatus;
                e.AutoGenerated = false;
                e.SourceModule = null;
                e.SourceId = null;
                e.PreviousStatus = null;
            }
            else
            {
                _db.ShiftEntries.Remove(e);
            }
        }
        await _db.SaveChangesAsync();
    }

    public async Task RevertVacationAsync(string employeeId, DateOnly dateFrom, DateOnly dateTo, int sourceId)
    {
        var entries = await _db.ShiftEntries
            .Where(x => x.EmployeeId == employeeId
                     && x.ShiftDate >= dateFrom
                     && x.ShiftDate <= dateTo
                     && x.SourceModule == "Vacation"
                     && x.SourceId == sourceId)
            .ToListAsync();

        foreach (var e in entries)
        {
            if (e.PreviousStatus != null)
            {
                e.ShiftType = e.PreviousStatus;
                e.AutoGenerated = false;
                e.SourceModule = null;
                e.SourceId = null;
                e.PreviousStatus = null;
            }
            else
            {
                _db.ShiftEntries.Remove(e);
            }
        }
        await _db.SaveChangesAsync();
    }
}
