export const mockData = [
  { id: "augsburg",        name: "Augsburg",           city: "Augsburg",        country: "DE", required: "07:30-12:00", status: "covered",   agents: [] },
  { id: "bamberg",         name: "Bamberg",            city: "Bamberg",         country: "DE", required: "08:00-16:00", status: "covered",   agents: [] },
  { id: "brokdorf",        name: "Brokdorf",           city: "Brokdorf",        country: "DE", required: "07:30-15:00", status: "covered",   agents: [] },
  { id: "denbosch",        name: "Denbosch",           city: "s-Hertogenbosch", country: "NL", required: "08:00-17:00", status: "covered",   agents: [] },
  { id: "dortmund",        name: "Dortmund",           city: "Dortmund",        country: "DE", required: "08:00-16:30", status: "covered",   agents: [] },
  { id: "emmerthal",       name: "Emmerthal",          city: "Emmerthal",       country: "DE", required: "08:30-15:30", status: "covered",   agents: [] },
  { id: "essenbach",       name: "Essenbach",          city: "Essenbach",       country: "DE", required: "08:00-15:30", status: "covered",   agents: [] },
  { id: "essen-bp1",       name: "Essen BP1",          city: "Essen",           country: "DE", required: "09:00-16:30", status: "uncovered", agents: [] },
  { id: "essen-tk1",       name: "Essen TK1",          city: "Essen",           country: "DE", required: "08:00-16:00", status: "uncovered", agents: [] },
  { id: "furstenwalde",    name: "Furstenwalde",       city: "Fürstenwalde",    country: "DE", required: "08:00-15:00", status: "covered",   agents: [] },
  { id: "grafenrheinfeld", name: "Grafenrheinfeld",    city: "Grafenrheinfeld", country: "DE", required: "07:30-15:00", status: "covered",   agents: [] },
  { id: "hamburg",         name: "Hamburg",            city: "Hamburg",         country: "DE", required: "08:00-17:00", status: "covered",   agents: [] },
  { id: "hannover",        name: "Hannover",           city: "Hannover",        country: "DE", required: "09:00-12:00", status: "covered",   agents: [] },
  { id: "helmstedt",       name: "Helmstedt",          city: "Helmstedt",       country: "DE", required: "08:00-13:00", status: "covered",   agents: [] },
  { id: "munchen",         name: "Munchen",            city: "München",         country: "DE", required: "09:30-12:00", status: "uncovered", agents: [] },
  { id: "neu-isenburg",    name: "Neu-Isenburg",       city: "Neu-Isenburg",    country: "DE", required: "08:00-16:30", status: "covered",   agents: [] },
  { id: "pfaffenhofen",    name: "Pfaffenhofen",       city: "Pfaffenhofen",    country: "DE", required: "08:00-17:00", status: "covered",   agents: [] },
  { id: "regensburg",      name: "Regensburg",         city: "Regensburg",      country: "DE", required: "08:00-17:00", status: "covered",   agents: [] },
  { id: "saarbrucken",     name: "Saarbrucken",        city: "Saarbrücken",     country: "DE", required: "09:00-16:00", status: "uncovered", agents: [] },
  { id: "salzgitter",      name: "Salzgitter",         city: "Salzgitter",      country: "DE", required: "08:00-13:00", status: "covered",   agents: [] },
  { id: "stadland",        name: "Stadland",           city: "Stadland",        country: "DE", required: "09:15-15:00", status: "covered",   agents: [] },
]
