using GSDDashboard.API.Data;
using GSDDashboard.API.Data.Models;
using GSDDashboard.API.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;

namespace GSDDashboard.API.Modules.SubstituteAccept;

public record AcceptSubstituteRequest(
    string EmployeeId,
    string LocationCode,
    string Date,
    string? ShiftStart,
    string? ShiftEnd,
    string? SourceType
);

public static class SubstituteAcceptEndpointMapper
{
    public static void MapSubstituteAcceptEndpoints(this WebApplication app)
    {
        app.MapPost("/api/wic/substitutes/accept", async (
            AcceptSubstituteRequest req,
            GSDContext db,
            ILoggerFactory loggerFactory) =>
        {
            if (string.IsNullOrEmpty(req.EmployeeId) || string.IsNullOrEmpty(req.LocationCode))
                return Results.BadRequest(new { error = "EmployeeId and LocationCode are required." });

            if (!DateOnly.TryParse(req.Date, out var date))
                return Results.BadRequest(new { error = "Invalid date format. Expected yyyy-MM-dd." });

            var location = await db.WicLocations
                .FirstOrDefaultAsync(l => l.LocationCode == req.LocationCode && l.IsActive);
            if (location == null)
                return Results.NotFound(new { error = $"Location '{req.LocationCode}' not found." });

            // Look up opening hours to populate WorkingShift on the WicShiftEntry
            int dow = (int)date.DayOfWeek;
            var allHoursForSub = await db.WicOpeningHours.ToListAsync();
            var hours = WicHoursResolver.Resolve(allHoursForSub, req.LocationCode, dow, date);
            string openTime  = hours?.OpenTime  ?? req.ShiftStart ?? "08:00";
            string closeTime = hours?.CloseTime ?? req.ShiftEnd   ?? "17:00";
            string workingShift = $"{openTime}-{closeTime}";

            var employee = await db.Employees
                .FirstOrDefaultAsync(e => e.EmployeeId == req.EmployeeId && e.IsActive);
            if (employee == null)
                return Results.NotFound(new { error = $"Employee '{req.EmployeeId}' not found." });

            // AgentTask column is MaxLength(20) — truncate display name if needed
            var agentTask = (location.DisplayName?.Length ?? 0) > 20
                ? location.DisplayName![..20]
                : location.DisplayName ?? req.LocationCode[..Math.Min(20, req.LocationCode.Length)];

            // Update existing ShiftEntry for the date, or create a new one
            var shift = await db.ShiftEntries
                .FirstOrDefaultAsync(s => s.EmployeeId == req.EmployeeId && s.ShiftDate == date);

            if (shift != null)
            {
                shift.ShiftType    = ShiftTypes.WicDuty;
                shift.IsWicDuty    = true;
                shift.AgentTask    = agentTask;
                shift.SourceModule = "SUBSTITUTE";
                if (req.ShiftStart != null) shift.ShiftStart = req.ShiftStart;
                if (req.ShiftEnd   != null) shift.ShiftEnd   = req.ShiftEnd;
            }
            else
            {
                db.ShiftEntries.Add(new ShiftEntry
                {
                    EmployeeId    = req.EmployeeId,
                    ShiftDate     = date,
                    ShiftType     = ShiftTypes.WicDuty,
                    IsWicDuty     = true,
                    AgentTask     = agentTask,
                    ShiftStart    = req.ShiftStart,
                    ShiftEnd      = req.ShiftEnd,
                    SourceSheet   = "SUBSTITUTE",
                    SourceModule  = "SUBSTITUTE",
                    AutoGenerated = true
                });
            }

            // Upsert WicShiftEntry so CoverageEvaluator and WicCardsService can count this substitute.
            // Both services query WicShiftEntries WHERE IsOnSite = 1 AND SupportLocation = loc.DisplayName.
            var wicShift = await db.WicShiftEntries
                .FirstOrDefaultAsync(w => w.EmployeeId == req.EmployeeId && w.ShiftDate == date);
            if (wicShift != null)
            {
                wicShift.SupportLocation = location.DisplayName;
                wicShift.IsOnSite        = true;
                wicShift.IsOffDay        = false;
                wicShift.IsGSDDay        = false;
                wicShift.WorkingShift    = workingShift;
                wicShift.Task            = "WIC";
            }
            else
            {
                db.WicShiftEntries.Add(new WicShiftEntry
                {
                    EmployeeId      = req.EmployeeId,
                    ShiftDate       = date,
                    DayOfWeek       = date.DayOfWeek.ToString(),
                    SupportLocation = location.DisplayName,
                    IsOnSite        = true,
                    IsGSDDay        = false,
                    IsOffDay        = false,
                    WorkingShift    = workingShift,
                    Task            = "WIC",
                });
            }

            db.SubstitutionHistory.Add(new SubstitutionHistory
            {
                EmployeeId   = req.EmployeeId,
                LocationCode = req.LocationCode,
                Date         = date,
                SourceType   = req.SourceType,
                AssignedAt   = DateTime.UtcNow
            });

            await using var tx = await db.Database.BeginTransactionAsync();
            try
            {
                await db.SaveChangesAsync();
                await tx.CommitAsync();
            }
            catch (DbUpdateException ex)
            {
                await tx.RollbackAsync();
                var logger = loggerFactory.CreateLogger("SubstituteAccept");
                logger.LogError(ex, "SubstituteAccept failed for {EmployeeId} at {LocationCode} on {Date}",
                    req.EmployeeId, req.LocationCode, req.Date);
                return Results.Conflict(new { error = "Accept failed — a concurrent change may have occurred. Please refresh and retry." });
            }

            return Results.Ok(new
            {
                success      = true,
                employeeName = employee.FullName ?? req.EmployeeId,
                displayName  = location.DisplayName,
                date         = date.ToString("yyyy-MM-dd")
            });
        }).WithTags("WIC");
    }
}
